/**
 * This file is auto-generated by idlpp
 * 
 * Source: HelloWorldData.idl
 * Generated on: 2019-10-22T10:46:43-0400
 * OpenSplice 6.10.3
 */
using DDS;
using System.Runtime.InteropServices;

namespace HelloWorldData
{
    #region Msg
    [StructLayout(LayoutKind.Sequential)]
    public sealed class Msg
    {
        public int userID;
        public string message = string.Empty;
        public double longitude_ul;
        public double lattitued_ul;
        public double longitude_lr;
        public double lattitude_lr;
    };
    #endregion

}

